"""Highly divisible triangular number

[Problem 12](https://projecteuler.net/problem=12)

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

from pyprimes import factors
from itertools import chain, combinations

def all_divisors_primes(n):
  finalset = []
  primefactors = factors(n)
  powerset = chain.from_iterable(combinations(primefactors, r) for r in range(1, len(primefactors) + 1))
  for s in powerset:
    divisor = 1
    for d in s:
      divisor *= d
    finalset.append(divisor)
  
  finalset.insert(0, 1)
  
  return list(set(finalset))

n = 0
nthValue = 0
divisor_count = 0
max_divisor_count = 0

while divisor_count < 500:
  n += 1
  nthValue += n
  divisor_count = len(all_divisors_primes(nthValue))

print(nthValue)
