"""Even Fibonacci numbers

Problem 2

https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

> 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

highestFibonacciNumberToSum = 4000000

fib0, fib1, accumulator = 1, 2, 0

while fib0 <= highestFibonacciNumberToSum:
  if fib0 % 2 == 0: accumulator += fib0
  fib0, fib1 = fib1, fib0 + fib1

print(accumulator)
